### ISSUE TITLE
nrf-mpsl-sys bindings hardcoded to either nrf52840/nrf5340? 

### ISSUE THREAD

**Issue by plaes** [alexmoon/nrf-sdc#30]
I noticed that current binding generator seems to generate bindings only for nrf52840 or nrf5340 based on build target architecture: 
https://github.com/alexmoon/nrf-sdc/blob/ba9cf5fd493281460d11901978d125b2f5451cba/nrf-mpsl-sys/build.rs#L34-L38

The `chip` then gets passed to bindgen as define:
https://github.com/alexmoon/nrf-sdc/blob/ba9cf5fd493281460d11901978d125b2f5451cba/nrf-mpsl-sys/build.rs#L63

Does this mean that my nrf52832 example only works by accident? :)

**Comment by alexmoon** [comment]
Yeah, that’s a good point. The libs don’t care about which device it is, but there may be different constants depending on the chip. We should add features for each chip and set the chip appropriately.
