### ISSUE TITLE
Requirement for embassy-nrf "unstable-pac" feature

### ISSUE THREAD

**Issue by plaes** [alexmoon/nrf-sdc#32]
At current state, MSPL requires access to two peripherals (`clock` and `radio`) through `pac` API which is hidden behind `unstable-pac` feature:
https://github.com/alexmoon/nrf-sdc/blob/ca480b8bb288727a7efed11e295854702226dd45/nrf-mpsl/src/mpsl.rs#L18-L20

And SDC requires additionally `AAR` and `ECB` peripherals which currently lack "non-stable" drivers:
https://github.com/alexmoon/nrf-sdc/blob/ca480b8bb288727a7efed11e295854702226dd45/nrf-sdc/src/sdc.rs#L31-L33

There is now a `radio` driver implementation in embassy: https://github.com/embassy-rs/embassy/tree/main/embassy-nrf/src/radio

**Comment by alexmoon** [comment]
These crates do not require HAL support for those devices.

The `unstable-pac` feature in `embassy-nrf` just re-exports the `pac` crate as a module of `embassy-nrf`. It is not needed for these crates.

**Comment by plaes** [comment]
Ok, I was hoping to eventually use `PeripheralRef<'d, peripherals::FOO>` for these as well.

**Comment by alexmoon** [comment]
Ah, ok. That would be nice, but `embassy-nrf` doesn't have peripherals defined for most of those. Once you have dropped the sdc and mpsl structs, it is safe to `steal` those peripherals back. I'd be happy to accept a PR for turning `RADIO` into a `PeripheralRef`.
