### ISSUE TITLE
SoftwareVBusDetect for USB peripheral

### ISSUE THREAD

**Issue by pperanich** [alexmoon/nrf-sdc#36]
Hi, I am starting to use [trouble](https://github.com/embassy-rs/trouble) with a custom device that uses an nrf52840, and would like to have the ability to support both BLE and USB comms. Currently, the main blocker is that both nrf-sdc and embassy-nrf usb vbus both require binding the `POWER_CLOCK`. There is a `SoftwareVbusDetect` implementation available that has previously shown working with `nrf-softdevice` at https://github.com/embassy-rs/nrf-softdevice/issues/194#issuecomment-1744893871. Would it be feasible to do something similar in nrf-sdc, and expose a `SoftwareVbusDetect` static that the library manges? See also https://github.com/embassy-rs/embassy/pull/810

**Comment by alexmoon** [comment]
You can bind the POWER_CLOCK interrupt to multiple handlers using the bind_interrupts! macro. There's no need for `SoftwareVbusDetect` for the softdevice controller.

**Comment by pperanich** [comment]
Thanks! Didn't realize that was possible.
